### ISSUE TITLE
minor comment on PLUGINS section of README

### ISSUE THREAD

**Issue by LeeDr** [jeffgeiger/PetELK#1]
From the README.md;

PLUGINS: The beta version of the Elastic X-Pack plugin has been installed. This includes authentication, graph analysis, timelion, etc.

You might want to mention that these are commercial plugins with a 30 day trial license just so people aren't surprised when some functionality stops working.  It's up to you.

Timelion is now built into Kibana 5.0 so it's not part of X-Pack.

Monitoring and Reporting are both features of X-Pack.

Suggestion;

PLUGINS: The beta version of the Elastic X-Pack plugin has been installed. This includes authentication, graph analysis, monitoring, and reporting.  This is a commercial plugin with a 30 day trial license.

**Comment by jeffgeiger** [comment]
Fixed.  Thanks!
